#!/usr/bin/env python3
"""Merge public upstream changes and publish an explicitly automated activity log."""

import argparse
from datetime import datetime, timezone
import fcntl
import json
import os
from pathlib import Path
import subprocess
import sys


def git(repo, *args):
    result = subprocess.run(
        ["git", "-c", "core.hooksPath=/dev/null", "-C", str(repo), *args],
        text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=900,
        env={**os.environ, "GIT_TERMINAL_PROMPT": "0"},
    )
    if result.returncode:
        raise RuntimeError(f"git {args[0]} failed: {result.stderr.strip()}")
    return result.stdout.strip()


def sync_one(root, owner, item, now):
    repo = root / "repos" / item["name"]
    branch = item["branch"]
    source = item["source"]
    expected_origin = item["origin"]
    if git(repo, "remote", "get-url", "origin") != expected_origin:
        raise RuntimeError("Origin does not match the configured destination")
    expected_upstream = item.get("upstream", f"https://github.com/{source}.git")
    if git(repo, "remote", "get-url", "upstream") != expected_upstream:
        raise RuntimeError("Upstream does not match the configured public source")
    if git(repo, "symbolic-ref", "--short", "HEAD") != branch:
        raise RuntimeError(f"Expected branch {branch}")
    if git(repo, "status", "--porcelain", "--untracked-files=all"):
        raise RuntimeError("Worktree has changes; leaving them untouched")
    git(repo, "fetch", "--no-tags", "origin", branch)
    git(repo, "merge", "--ff-only", f"origin/{branch}")
    git(repo, "fetch", "--no-tags", "upstream", branch)
    upstream_sha = git(repo, "rev-parse", f"upstream/{branch}")
    imported_count = int(git(repo, "rev-list", "--count", f"HEAD..upstream/{branch}"))
    if imported_count:
        try:
            git(repo, "merge", "--no-edit", f"upstream/{branch}")
        except Exception:
            # Git merge starts from a clean worktree, so abort preserves local commits.
            git(repo, "merge", "--abort")
            raise
    # One log entry per six-hour UTC window, including retries after a failed push.
    slot = now.strftime("%Y-%m-%d") + f"T{(now.hour // 6) * 6:02d}:00Z"
    relative_log = Path(".github-sync/activity") / (now.strftime("%Y-%m") + ".md")
    log = repo / relative_log
    old = log.read_text() if log.exists() else (
        "# Automated upstream sync activity\n\n"
        "Generated by a scheduled maintenance job. These entries record automated "
        "checks and imports, not human development work.\n\n"
        "| UTC window | Checked at (UTC) | Upstream commit | Imported commits |\n"
        "| --- | --- | --- | --- |\n"
    )
    if f"| {slot} |" not in old:
        log.parent.mkdir(parents=True, exist_ok=True)
        timestamp = now.isoformat(timespec="seconds")
        log.write_text(old + f"| {slot} | {timestamp} | `{upstream_sha}` | {imported_count} |\n")
        git(repo, "add", "--", str(relative_log))
        git(repo, "commit", "-m", f"chore: automated upstream sync log {slot} [skip ci]",
            "-m", "Co-Authored-By: Codex <noreply@openai.com>")
    git(repo, "push", "origin", f"HEAD:refs/heads/{branch}")
    local = git(repo, "rev-parse", "HEAD")
    remote = git(repo, "ls-remote", "origin", f"refs/heads/{branch}").split()[0]
    if local != remote:
        raise RuntimeError("Remote verification did not match the local commit")
    print(f"{now.isoformat()} OK {owner}/{item['name']} {local} imported={imported_count}", flush=True)
    return local


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.home())
    parser.add_argument("--repo", help="Only sync this configured repository")
    args = parser.parse_args()
    root = args.root.resolve()
    state = root / "state"
    state.mkdir(parents=True, exist_ok=True)
    with (state / "sync.lock").open("w") as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            print("Another sync is running; skipped", flush=True)
            return 0
        manifest = json.loads((root / "manifest.json").read_text())
        entries = manifest["repositories"]
        if args.repo:
            entries = [item for item in entries if item["name"] == args.repo]
            if not entries:
                parser.error("Unknown repository")
        now = datetime.now(timezone.utc)
        results = {}
        for item in entries:
            try:
                sha = sync_one(root, manifest["owner"], item, now)
                results[item["name"]] = {"status": "ok", "sha": sha}
            except Exception as error:
                print(f"{now.isoformat()} ERROR {item['name']}: {error}", file=sys.stderr, flush=True)
                results[item["name"]] = {"status": "error", "error": str(error)}
        temporary = state / "last-run.json.tmp"
        temporary.write_text(json.dumps({"at": now.isoformat(), "repositories": results}, indent=2) + "\n")
        temporary.replace(state / "last-run.json")
        return int(any(item["status"] == "error" for item in results.values()))


if __name__ == "__main__":
    sys.exit(main())
